# Generated by Django 3.1.7 on 2021-03-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assess_id', models.AutoField(primary_key=True, serialize=False)),
                ('assess_name', models.CharField(max_length=255, verbose_name='Assessment Name')),
                ('assess_points', models.IntegerField(default=100, verbose_name='Assessment Points')),
                ('assess_time_limit', models.IntegerField(default=120, verbose_name='Time limit (mins.)')),
                ('module', models.CharField(max_length=255, verbose_name='Module ID')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_name', models.CharField(max_length=255, verbose_name='Assignment Name')),
                ('assign_desc', models.TextField(blank=True, verbose_name='Assignment Description')),
                ('assign_points', models.IntegerField(default=100, verbose_name='Points')),
                ('deadline', models.DateField(verbose_name='Submission Deadline')),
                ('module', models.CharField(max_length=255, verbose_name='Module ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255, unique=True, verbose_name='Course ID')),
                ('course_name', models.CharField(max_length=255, unique=True, verbose_name='Course Name')),
                ('course_desc', models.TextField(blank=True, verbose_name='Course Description')),
                ('days', models.CharField(max_length=255, verbose_name='Day')),
                ('timing', models.CharField(max_length=255, verbose_name='Timing')),
                ('mode', models.CharField(max_length=255, verbose_name='Instruction Mode')),
                ('instructor', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=255, verbose_name='Module Name')),
                ('module_desc', models.TextField(blank=True, verbose_name='Module Description')),
                ('module_type', models.CharField(choices=[('CW', 'Course Work'), ('AS', 'Assessment'), ('AT', 'Assignment'), ('PT', 'Project')], default='CW', max_length=24, verbose_name='Module Type')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearn.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_or_file', models.CharField(max_length=450, verbose_name='Link/File')),
                ('topic_type', models.CharField(choices=[('IL', 'Internal Link'), ('EL', 'External Link'), ('FL', 'File')], default='FL', max_length=24, verbose_name='Type of Topic')),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='ELearn.module')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.CharField(max_length=400, verbose_name='File')),
                ('assign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearn.assignment')),
                ('user_id', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='Question')),
                ('answer', models.CharField(choices=[('FI', 'Fill-in'), ('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='FI', max_length=24, verbose_name='Answer')),
                ('answer_text', models.TextField(blank=True, verbose_name='Answer')),
                ('question_type', models.CharField(choices=[('FI', 'Fill-in'), ('MCQ', 'Multiple Choice Question')], max_length=30, verbose_name='Question Type')),
                ('question_points', models.IntegerField(default=0, verbose_name='Points')),
                ('option_a', models.CharField(max_length=450, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=450, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=450, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=450, verbose_name='Option D')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearn.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/OLS/default_user.png', upload_to='profile_pics', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearn.course'),
        ),
        migrations.CreateModel(
            name='Assessment_Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('result', models.IntegerField(default=0, verbose_name='Result')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearn.assessment')),
                ('attempt_user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='ELearn.question')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearn.course'),
        ),
    ]
