# Generated by Django 3.1.7 on 2021-03-11 18:18

import ELearn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_file',
            field=models.FileField(blank=True, null=True, upload_to=ELearn.models.user_directory_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='link_or_file',
            field=models.CharField(max_length=450, verbose_name='Link'),
        ),
    ]
