# Generated by Django 3.1.7 on 2021-03-11 21:31

import ELearn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELearn', '0002_auto_20210311_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='link_or_file',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_url',
            field=models.CharField(default='Elearn', max_length=450, verbose_name='Specify URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_file',
            field=models.FileField(blank=True, null=True, upload_to=ELearn.models.user_directory_path, verbose_name='Upload file'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(choices=[('URL', 'URL'), ('FL', 'File')], default='FL', max_length=24, verbose_name='Type of Topic'),
        ),
    ]
