# Generated by Django 3.1.7 on 2021-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELearn', '0003_auto_20210311_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1000, verbose_name='Question'),
        ),
    ]
