# Generated by Django 3.1.7 on 2021-03-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELearn', '0006_auto_20210324_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
