# Generated by Django 3.1.7 on 2021-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELearn', '0009_auto_20210325_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.CharField(default='admin', max_length=255, verbose_name='To'),
        ),
    ]
