# Generated by Django 3.1.7 on 2021-03-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELearn', '0011_auto_20210325_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('content', models.TextField(verbose_name='Comment')),
            ],
        ),
    ]
