# Generated by Django 3.1.7 on 2021-03-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearn', '0018_auto_20210326_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('project_desc', models.TextField(blank=True, verbose_name='Project Description')),
                ('project_points', models.IntegerField(default=100, verbose_name='Points')),
                ('deadline', models.DateField(verbose_name='Submission Deadline')),
                ('module', models.CharField(max_length=255, verbose_name='Module ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearn.course')),
            ],
        ),
    ]
